### ISSUE TITLE
Transaction errors. "Your request has been rate limited. Pleas wait longer between subsequent requests."

### ISSUE THREAD

**Issue by dimateus** [brandedcrate/payjunction-php#1]
Payjunction api has rate limits. The actual rule is ‘no more than 1 transaction per 100 milliseconds’. 
Almost all transactions was declined with error  "Your request has been rate limited".
Because we have 2 requests with this culr options in curlInit() method
curl_setopt($this->curl, CURLOPT_HTTPAUTH, CURLAUTH_ANY);
curl_exec() was executed only 1 time.

— — 2015-03-31 17:22:04,610  requestId=2d0cb529-1634-**************_bacfae  authentication failed, no Authorization header found
— — 2015-03-31 17:22:04,667  requestId=c6f204fb-38ab-48af-**_**********\* rate limit exceeded ipAddress=***********\* apiRateLimit=10

I have fixed this by changing option to this one
curl_setopt($this->curl, CURLOPT_HTTPAUTH, CURLAUTH_BASIC);

**Comment by stevecrozz** [comment]
Thanks for the report. I have another theory about what was happening. You were probably making requests at a high rate, and PayJunction applied the rate limit. It takes some time for the rate limit to go away. My guess is that you made this change at the same time the rate limit expired (just by chance). Is that possible?

If you think not, then can you provide an example that fails consistently?

**Comment by dimateus** [comment]
This bug appears on a single transaction. But i have it only on live endpoint.
And bug appears just sometimes.

Here is full answer of payjunciton support:

---

We examined the logs on our end, and I think I can see what the problem is, or at least what needs to be looked at. The actual rule is ‘no more than 1 transaction per 100 milliseconds’. When we check the log looking at the transaction, this is what we are seeing:

— — 2015-03-31 17:22:04,610  requestId=2d0cb529-1634-4550-b06f-508709bacfae  authentication failed, no Authorization header found
— — 2015-03-31 17:22:04,667  requestId=c6f204fb-38ab-48af-8df7-078707e2f258  rate limit exceeded ipAddress=********\* apiRateLimit=10

It seems that your server is sending one request without the http authentication header included (which is therefore blocked), and then immediately sending another request, which gets denied for arriving within 100 milliseconds of the first request.

---

When you setup CURLAUTH_ANY option. courl_exec makes 2 requests. First request for checking auth method.

**Comment by stevecrozz** [comment]
Thanks for the additional info. I'll look into this today and release a new version of this module if I can confirm.

**Comment by stevecrozz** [comment]
I made the update you suggested and released a new package v0.4.0: https://packagist.org/packages/brandedcrate/payjunction#0.4.0
